<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Catalogo.Api</RootNamespace>
    <AssemblyName>Catalogo.Api</AssemblyName>
    <!-- TODO-03: activar GenerateDocumentationFile cuando la documentacion XML publica este completa. -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

</Project>
